### PR TITLE
Modularize scripts to make gwvet noarch: python

### PR DESCRIPTION
**Pull request by alurban**
This PR accomplishes a few related things:

* Modularize the bash scripts under `bin` to make VET a platform-independent `noarch: python` package
* Refactor items under `setup.py` into `setup.cfg`
* Handle Travis CI through Conda
* Tidy up flake8 linter complaints

cc @duncanmmacleod, @brennanhughey, @areeda, @eagoetz, @robertbruntz

### CODE REVIEW

**Comment by eagoetz** [comment]
@alurban I don't have any significant comments. It looks like fairly reasonable changes to me. Have you, or someone, vetted (pun perhaps intended) that the code changes to modularize the scripts does not change the behaviour of what is expected?

**Comment by alurban** [comment]
@eagoetz I haven't vetted that yet outside of running help documentation (which we know works because it's part of the CI infrastructure). Do you have strong feelings about whether that should be done now, or whether it can be tested later in-production? My argument for the latter is as follows:

* Downstream LVK reviewers are much more familiar with typical use cases for this software
* It satisfies a quasi-urgent need to get gwvet-1.0.0 out before I leave
* If anything is broken, it can be fixed later in a point release, which is a useful relatively low-stakes way for you guys to practice

What do you think?

**Comment by eagoetz** [comment]
No, I think that's fine. If we find out something needs to change based on the downstream users reporting issues, we can make a new PR.

**Review by eagoetz — APPROVED** [review]
This looks like a reasonable set of changes to me; though, admittedly, I'm a not an complete expert on all of these updates.

**Review by areeda — APPROVED** [review]
LGTM

**Review by robertbruntz — APPROVED** [review]
LGTM

**Pull request merged**
